internal/cmd/scraper/scraper.go

We were sending to a wrong endpoint that doesn't accept the licenseKey

Update to infra metrics endpoint

---

cmd/nri-prometheus/config.go
deploy/nri-prometheus.tmpl.yaml

* Better representation of the scrape timeout default value
* Fix the scrape timeout default value in the example configuration
* Fix the default value of `require_scrape_enabled_label_for_nodes` to match what is said in the default configuration

Documentation improvements and matching with the codebase

---

README.md
cmd/nri-prometheus/config.go
internal/cmd/scraper/scraper.go
internal/histogram/bucket.go
internal/histogram/percentile.go
internal/histogram/percentile_test.go
internal/integration/emitter.go
internal/integration/emitter_test.go
internal/integration/fetcher.go
internal/integration/fetcher_test.go

This PR adds support for processing summaries and histograms.
Most of the work of this PR was made by @MrAlias when the project was hosted on a private repository, so all the credit should go to him, I just rebased, and did some minor improvements.
The implementation follows the the [New Relic's guidelines for higher-level metric abstractions](https://github.com/newrelic/newrelic-exporter-specs/blob/master/Guidelines.md):
- For summaries, the quantiles are transformed and sent as percentiles.
- For histograms, predefined percentiles are calculated and sent along with the buckets. By default the 50, 95 and 99 percentile are calculated, this value can be overriden via the `percentiles` configuration option. 
The `histogram` package had to be copied from the official prometheus one, because …

Add support for summaries and histograms

---

CHANGELOG.md
deploy/nri-prometheus.tmpl.yaml

The default configuration is very restrictive. It filters almost all the metrics and it makes for a hard on-boarding.
The feedback we have received tells us that users prefer to have the integration send all the metrics available and then start refining the amount of data they send.
This PR comments the default transformation, it's not deleted because so users can use it as an guideline and example on how to configure transformations.

Comment default transformations from manifest

---

CHANGELOG.md
README.md
cmd/k8s-target-retriever/main.go
internal/cmd/scraper/scraper.go
internal/pkg/endpoints/kubernetes.go
internal/pkg/endpoints/kubernetes_test.go
vendor/vendor.json

This PR fixes the bug that adds newly created Pod-targets without an ipAddress and caches them, which makes them unscrabable unless you restart POMI. 
It also includes a simple program that runs the KubernetesTargetRetriever locally so you can debug it.

FSI-1155: Don't scrape pods without a valid PodIP

---

internal/pkg/endpoints/endpoints_test.go
internal/pkg/endpoints/kubernetes.go
internal/pkg/endpoints/kubernetes_test.go

The manual construction of the struct `url.URL` was considering the URL
parameters as a part of the URLs's path and this was causing encoding
issues on some characters.
As an example, if a pod had the `prometheus.io/path` annotation set to
`/metrics?format=prometheus` we would end up querying
`/metrics%3Fformat=prometheus`.

Fix bug with URL encoded params

---

.travis.yml

Because of [this security constraint](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions), we can't execute the `snyk test` step on travis for pull requests.

Don't run snyk on PR builds

---

CHANGELOG.md
deploy/nri-prometheus.tmpl.yaml
internal/cmd/scraper/scraper.go
internal/integration/emitter.go

Changes the values for the telemetry emitter delta calculator expiration
age and expiration check interval from 30 seconds to 5 minutes. Also
adds the following configuration options for setting each setting:
- telemetry_emitter_delta_expiration_age
- telemetry_emitter_delta_expiration_check_interval
This fixes the issue of missing datapoints for counters when the scrape
interval was taking longer than the delta expiration check interval and age.

Change delta calcaulator defaults.

---

.goreleaser.yml
cmd/nri-prometheus/main.go
tools/deploy-yaml/main.go

Whenever there is a prerelease version `vX.Y.Z-rc` it will only upload the corresponding `vX.Y.Z-rc` yaml and docker tag

Add pre-release support to release pipeline

---

cmd/nri-prometheus/config.go
deploy/local.yaml.example
deploy/nri-prometheus.tmpl.yaml
internal/cmd/scraper/scraper.go

**Use Case**
Sometimes we want to run the integration in an environment where autodiscovery is not needed or due to permission limitation cannot be performed. In this scenarios hundreds of error logs were shown together with failing request to k8s APIs.
Es: service account running the pod ha not visibility into the whole cluster.
```
time="2020-08-28T11:20:53Z" level=warning msg="couldn't list node resource, retrying" component=KubernetesAPI error="timeout reached, 60 retries executed. last error: nodes is forbidden: User \"system:serviceaccount:new-relic:nri-prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
```
**Solution**
- A config option `enable_autodiscovery ` has been added in order to add the possibility to enable/disable autodiscovery.
- By …

feat(config): added config option to enable/disable autodiscovery

---

cmd/nri-prometheus/config.go
deploy/local.yaml.example
deploy/nri-prometheus.tmpl.yaml
internal/cmd/scraper/scraper.go

**Reason behind the change**
In the k8s manifests I noticed that the `--configfile ` argument was passed. However, such argument was ignored since the config file path was hardcoded.
After we moved to the infraSDK if an unexpected argument is passed an error is returned. Therefore after updating the manifest with the correct argument I added the old argument as an alias.
Be aware that we decided to change the config name since the agent pass the environment variable `CONFIG_PATH`

fix(k8sManifest): configfile added as alias of config_path

---

internal/integration/emitter.go
internal/integration/emitter_test.go
internal/integration/harvester_decorator.go

These values cannot be handled by NRDB, and POMI currently logs an error message for every single NaN/Infinite value it processes, which can be confusing.

Ignored Nan and Infinite float values

---

.github/workflows/helm.yml
Makefile

Uses PAT as secret for execute the helm chart version bumper since secrets.GITHUB_TOKEN is not allowed 
Removes snyk step from Make , since is already executing in GHA

fix: use personal token for helm bumper

---

cmd/nri-prometheus/config.go
internal/cmd/scraper/scraper.go
internal/integration/infra_sdk_emitter.go

Adds default value for:
* DefinitionFilesPath
* Emitter: uses `infra-sdk` when standalone is false and `telemetry` when is true (backward compatibility)
This PR fixes issue #83

fix: default configs emitter and definition path

---

internal/integration/infra_sdk_emitter.go
internal/integration/spec.go
internal/integration/spec_test.go

Moving from a Map to a slice of keyvalues to ensure ordering.
There were different ways assure the same, but I followed this approach to keep the logic as similar as possible to the initial one
The bug was causing entities to change the name due to label ordering:
```
github:10.0.2.2:9999:job:289885995:MDExOldvcmtmbG93UnVuMjg5ODg1OTk1
github:10.0.2.2:9999:job:MDExOldvcmtmbG93UnVuMjg5ODg1OTk1:289885995
```

fix(entityName): ensuring ordering of labels

---

internal/integration/spec.go
internal/integration/spec_test.go
internal/integration/test/prometheus_redis_bis.yml

This PR allows two exporter with same metric namespace to have different definition files . 
This approach just adds the entities from all definitions files that share the same service name to the same object. 
In the future the entity discovery mechanism should be replaced and this approach will no longer be needed.

feat: accept duplicated service definitions

---

go.mod
go.sum
internal/integration/infra_sdk_emitter_test.go

this updates the infra sdk module that contain a fix for `counter` type metrics.

fix: update sdk fixes count type metrics agent error

---

internal/integration/integration.go
internal/pkg/prometheus/prometheus.go

The metrics were not resetted properly and this was causing a possible leakage of them.
Before deleting kube-state-metric
```
nr_stats_discoveries_total{retriever="fixed"} 1
nr_stats_discoveries_total{retriever="kubernetes"} 1
nr_stats_fetches_total{target="demo.robustperception.io:9100"} 1
nr_stats_fetches_total{target="kube-dns"} 1
nr_stats_fetches_total{target="test-kube-state-metrics"} 1
nr_stats_integration_emit_total_duration_seconds{emitter="telemetry"} 20.027329149
nr_stats_integration_fetch_target_duration_seconds{target="demo.robustperception.io:9100"} 0.123778485
nr_stats_integration_fetch_target_duration_seconds{target="kube-dns"} 0.003789195
nr_stats_integration_fetch_target_duration_seconds{target="test-kube-state-metrics"} 0.013140416 …
```

fix(promMetrics): resetting metrics to avoid leakage

---

cmd/nri-prometheus/config.go
configs/nri-prometheus-config.yml.sample
deploy/local.yaml.example
deploy/nri-prometheus.tmpl.yaml
internal/cmd/scraper/scraper.go

This adds a config option to enable audit logging in the telemetry emitter. Sometimes this is useful to debug metric issues.

Add audit-logging setting

---

internal/cmd/scraper/scraper.go

The aim of the PR is to add to each metrics the data needed to customer and agents to properly detect the source of such data.
In particular two "categories" have been added:
- `collector` indicates the component sending the data. 
For example `nri-prometheus` in standalone mode sends metric with `collector.name=nri-prometheus`. If it sends metrics through the agent the  `collector.name=infrastructure-agent`
- `instrumentation` category contains info regarding the integration that fetched the data
The provider is currently hardcoded, but we might consider in the future to make it configurable through the SDK
We might add in the future more common attributes, for example `exporter` indicating the exporter and the version of the exporter exposing the data. So far we did not have a proper …

Collector and instrumentation info

---

load-test/.helmignore
load-test/Chart.yaml
load-test/README.md
load-test/templates/NOTES.txt
load-test/templates/_helpers.tpl
load-test/templates/deployment.yaml
load-test/templates/service.yaml
load-test/values.yaml

Fix #106 
This PR add a chart to generate prometheus load. 
It creates `n` services per deployment where `n` is `numberServicesPerDeploy`
The deployments can be configured with the array:
```
deployments:
- name: one
latency: "12"
latencyVariation: "0"
metrics: "https://raw.githubusercontent.com/newrelic/nri-prometheus/main/internal/cmd/scraper/testData/testData.prometheus"
#maxRoutines: ""
```
Notice that each values has default and that none of them is required to be unique:
Name of deployment: `<name>-lat<latency>-latvar<latencyVar>-<deployindex>`
Name of service: `<name>-lat<latency>-latvar<latencyVar>-<deployindex>-<serviceindex>`

Load Test chart

---

.goreleaser.yml

Linker flag `-X` allows to overwrite a variable value at link time give its import path. Right now, a relative import path is provided, which does not seem to work. This PR changes the path to be absolute, which I have confirmed to work on my local machine.
---
Fixes #114

goreleaser: use full import path in ldflags -X

---

configs/nri-prometheus-config.yml.sample
deploy/nri-prometheus.tmpl.yaml

config: add commented values for advanced config flags

---

.github/workflows/load_test.yml

This PR removes the load test on PR since it uses secrets and are not available for external users.

ci: remove load test from PR

---

.goreleaser.yml

The name structure of `nri-prometheus` was not the same to the one of other repos (es: nri-redis, nri-flex, etc)

feat(ci/cd): changing name structure of tar.gz

---

configs/nri-prometheus-config.yml.sample
deploy/local.yaml.example
deploy/nri-prometheus.tmpl.yaml

These definitions aren't ready to be used - it's better to remove it
from the config sample.

chore: remove definition path from config sample

---

internal/pkg/prometheus/prometheus.go

Hi there folks! 👋 
We're seeing some pretty wild flapping of our SLI which is a composition of 2 different metrics. We see this flapping on deploy.
We believe we've tracked this down to the behavior of nri-prometheus when a page is only partially loaded:
https://github.com/a-feld/prometheus-unexpected-eof
When a page is partially loaded, an `unexpected EOF` error is raised, but is squashed by the prometheus decoder. This PR exposes the `unexpected EOF` error (io.ErrUnexpectedEOF) and avoids only partially reporting metrics which can lead to weird behavior of metrics that are compositions in the UI.

Buffer the full page in the scraper to expose unexpected EOF.

---

.github/workflows/push_pr.yml

Previously, `push_pr` workflow would try to login to dockerhub (to prevent rate limiting) on each test job, using a repo secret. Since forks cannot access secrets this would make the `push_pr` fail for every PR coming from a fork.
This PR conditions the login step to the availability of the docker secret.

ci: condition docker login to secret availability

---

.github/workflows/load_test.yml
.github/workflows/push_pr.yml
cmd/k8s-target-retriever/main.go
cmd/nri-prometheus/config.go
deploy/local.yaml.example
deploy/nri-prometheus.tmpl.yaml
internal/cmd/scraper/scraper.go
internal/pkg/endpoints/endpoints.go
internal/pkg/endpoints/kubernetes.go
internal/pkg/endpoints/kubernetes_test.go
load-test/README.md
load-test/laod_test.sh

Fix https://github.com/newrelic/nri-prometheus/issues/27
The idea is that when a service is detected the underlying endpoints are fetched. For backward compatibility the metric directly coming from the service is kept
Two new config options have been added `ScrapeServices (default true)` and `ScrapeEndpoints(default false)`
After merging we should update documentation and the helm chart to ask for listing/watching permission on endpoints

 fix(endpoints): scrape endpoints and not services

---

internal/pkg/endpoints/kubernetes.go

Previously, path[0] was used which caused a panic for empty labels
This will _allow_ the use of an empty label value, which will be translated to "/"
Fixes #181

endpoints: check for path prefix with strings.HasPrefix

---

internal/pkg/endpoints/endpoints_test.go
internal/pkg/endpoints/kubernetes_test.go

That cuts down test execution time by half (from 2.7s to 1.3s in my
case).
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

internal/pkg/endpoints: run unit tests in parallel

---

internal/integration/bounded_harvester_test.go
internal/integration/emitter_test.go
internal/integration/fetcher_test.go
internal/integration/infra_sdk_emitter_test.go
internal/integration/roundtripper_test.go
internal/integration/rules_test.go
internal/integration/scrape_test.go
internal/integration/spec_test.go
internal/integration/telemetry_sdk_emitter_test.go
internal/pkg/endpoints/endpoints.go
internal/pkg/endpoints/endpoints_test.go
internal/pkg/endpoints/fixed.go
internal/pkg/endpoints/kubernetes.go
internal/pkg/endpoints/kubernetes_test.go
internal/pkg/endpoints/metrics.go
internal/pkg/endpoints/self.go

This PR brings various improvements to `internal/pkg/endpoints` and `internal/integration` packages like better formatting, imports, parallel tests. There is no functional changes, but I believe those changes should make code easier to read and understand.
There are some changes to exported types to simplify the APIs of internal packages.

internal: various improvements

---

internal/cmd/scraper/scraper.go
internal/integration/fetcher.go
internal/integration/infra_sdk_emitter.go
internal/integration/infra_sdk_emitter_test.go

This PR fixes https://github.com/newrelic/newrelic-coreint/issues/109
It also removes the following attributes from the metrics since they are not needed on the sdkV4 protocol:
- `nrMetricType`
- `promMetricType`
- `integrationVersion` this was replaced by `instrumentation.version` populated in the Agent from the Integration Metadata
- `integrationName`  this was replaced by `instrumentation.name` populated in the Agent from the Integration Metadata

feat(infra_emitter): add common attributes

---

.goreleaser.yml

In order to support the canary reroller we need latest image.
After this change we are going to have two images created: 
- nri-prometheus:latest for the stable channel
- nri-promatheus:latest-pre for the unstable channel

[CI/CD] publish latest and latest-pre image

---

internal/integration/infra_sdk_emitter.go

Moving to cumulative count, in the agent the delta is computed:
```go
case "cumulative-count":
c = Conversion{toTelemetry: Count{calculate: &Cumulative{get: s.calculator.delta.CountMetric}}}
//GetCumulativeCount creates a count metric from the difference between the values and
//timestamps of multiple calls.  If this is the first time the name/attributes
//combination has been seen then the `valid` return value will be false.
```

fix(infraSDK): using cumulativeCount to report deltas

---

internal/pkg/endpoints/kubernetes.go
internal/pkg/endpoints/kubernetes_test.go

- Adds scheme scraping with a deafult set to `http`.
- Cleans up the endpoints/service/pod target logic to go though the same
pathways.
- Avoids unnecessary sprintf based URL creation and parsing.
- Test changes:
- Bad annotations now cause a fallback to default scraping instead of
returning nothing.
- Not using sprintf for URL creation properly escapes paths. So
`prometheus.io/path` should be a path and shouldn't include query
params. `?` in paths get URL escaped now.
Fixes #234
Signed-off-by: Vihang Mehta <vihang@pixielabs.ai>

Add support for `prometheus.io/scheme`

---

internal/integration/fetcher.go
internal/integration/rules.go
internal/integration/rules_test.go

allow metric filtering by metric type
Ex.
```
transformations:
- description: "General processing rules"
ignore_metrics:
- metric_types:
- "histogram"
```
The use case is the ability to ignore histograms which generate a large number of (unused) metrics.
```
argocd_redis_request_duration_bucket{hostname="argocd-application-controller-1",initiator="argocd-application-controller",le="0.01"} 2.791635e+06
argocd_redis_request_duration_bucket{hostname="argocd-application-controller-1",initiator="argocd-application-controller",le="0.05"} 3.347797e+06
argocd_redis_request_duration_bucket{hostname="argocd-application-controller-1",initiator="argocd-application-controller",le="0.1"} 3.582787e+06
argocd_redis_request_duration_bucket{hostname="argocd-application-controller-1",initiator="argocd-applic …
```

Ignore metrics by type

---

internal/pkg/prometheus/prometheus.go
internal/pkg/prometheus/prometheus_test.go

Adds the `Accept` header with the same content as the Prometheus Server.
Removes the "application/json" content-type form the header as well since only prometheus text metrics can be parsed by this Getter 
fixes #252

Add prometheus accept header

---

internal/integration/fetcher.go
internal/pkg/endpoints/endpoints.go
internal/pkg/endpoints/kubernetes.go

Prior to this PR, `nri-prometheus` was sending the Kubernetes Service Account Token to endpoints that probably wouldn't need them. This PR introduces a flag in the `Target` struct, `UseBearer`, which is set to `true` for nodes only. Fetcher reacts to this flag by using a specific HTTP client that adds the token as an `Authorization` header.

endpoints: add UseBearer flag and set it to true for nodes

---

internal/pkg/endpoints/kubernetes.go
internal/pkg/endpoints/kubernetes_test.go

As prometheus server abuses label concatenation using regexes, the `prometheus.io/path` annotation can be abused to include query paramenters such as `prometheus.io/path: /metrics?format=foo`, and this will be handled fine by it.
While this behavior is likely accidental, it has been set as standard and some edge cases rely upon it.
This PR allows `nri-prometheus` to support this use case, by pre-parsing the `prometheus.io/path` annotation into `path` and `query` before building the `url.URL` object.

endpoints/kubernetes: parse query args from prometheus.io/path

---

internal/pkg/endpoints/kubernetes.go
internal/pkg/endpoints/kubernetes_test.go

Query params were not included whenever a port was specified

fix(query): query params not included if port specified

---

.github/workflows/nightly.yaml

Closes https://github.com/newrelic/nri-prometheus/issues/211.
This PR adds a new GHA workflow, which will build and push Docker images daily.

Add nightly builds

---

CHANGELOG.md
cmd/nri-prometheus/config.go
cmd/nri-prometheus/config_test.go
go.mod
go.sum
internal/cmd/scraper/scraper.go
internal/integration/fetcher.go
internal/integration/fetcher_test.go
internal/integration/helpers_test.go
internal/integration/integration_test.go
internal/pkg/prometheus/prometheus.go
internal/pkg/prometheus/prometheus_test.go

The purpose of the PR is to remove from the accept header the format we actually do not support such as `openmetrics` and `*/*`. At the same time 
Related to https://github.com/newrelic/nri-prometheus/issues/252. In order to support a specific use-case we added as acceptHeader the very same value the prometheus server had. However, the prometheus server has two different parsers one for `plain/text` and the other one for `application/openmetrics-text`.
We currently leverage `expfmt.FmtText` to formatdata. `github.com/prometheus/common/expfmt` also supports `application/openmetrics-text` but merely up to 0.0.1
Fix https://github.com/newrelic/nri-prometheus/issues/313 
Fix https://github.com/newrelic/nri-prometheus/issues/315
---
For example configuring:
```
scrape_accept_header: …
```

fix(acceptHeader): rollback to text/plain

---

cmd/nri-prometheus/config_test.go
cmd/nri-prometheus/testdata/config-with-legacy-entity-definitions.yaml
internal/cmd/scraper/scraper_test.go
internal/pkg/endpoints/endpoints.go
internal/pkg/endpoints/fixed.go

Attaching the token to all request would be a security issue. 
Therefore the decision was taken to attach it merely for static targets whenever the user was explicitly asking for it.

feat(useBearer): expose the config for static targets

---

CHANGELOG.md
charts/nri-prometheus/Chart.yaml
charts/nri-prometheus/README.md
charts/nri-prometheus/README.md.gotmpl
charts/nri-prometheus/values.yaml

Bumping the image to [v2.16.3](https://github.com/newrelic/nri-prometheus/releases/tag/v2.16.3) exposing the `use_bearer` option.
Several dependencies were also updated

chore(chart): bump to new version of the integration

---

charts/nri-prometheus/Chart.yaml
charts/nri-prometheus/README.md

Relates to https://github.com/newrelic/helm-charts/issues/845.
Fix url to point to the proper branch.

Fix helm chart url

---

CHANGELOG.md
go.mod
go.sum
internal/integration/rules.go
internal/integration/rules_test.go

Fix https://github.com/newrelic/nri-prometheus/issues/344
The previous implementation was counting prefixes and metricTypes from all rules when applying the excludes.
With the old implementation the testcase TestIgnoreRules was starting to fail adding a prefix without any effect to a different rule.
The risk of solving this bug is breaking the config of users relying on a bug to collect metrics

NEWRELIC-3719 fix(filters): multiple rules bug

---

configs/nri-prometheus-config.yml.sample

The default value for `scrape_timeout` in the config example comment is misleading because wasn't reflecting the [default value actually being used](https://github.com/newrelic/nri-prometheus/blob/chore/update-config-examples/cmd/nri-prometheus/config.go#L96).

chore: fix config example default values

---

.github/workflows/load_test.yml
.github/workflows/push_pr.yml
charts/nri-prometheus/Chart.yaml
charts/nri-prometheus/tests/configmap_test.yaml
charts/nri-prometheus/tests/deployment_test.yaml
charts/nri-prometheus/tests/labels_test.yaml

We were not updating the chart version due to https://github.com/renovatebot/renovate/issues/13968
We should understand if we want to move the version to the values.yaml or change the renovate config to support regexes

chore(pomi): update appVersion

---

build/Dockerfile

We decided to pin golang version and [automerge them](https://github.com/newrelic/coreint-automation/commit/398ade41391d36da64320e123d832566d201601b)

chore(golang): pin golang version

---

CHANGELOG.md
internal/pkg/endpoints/kubernetes.go
internal/pkg/endpoints/kubernetes_test.go

When `prometheus.io/port` annotation is set, no matter what, it just creates the target according the annotation value.
This potentially could make unnecessary calls to non-exposed port that end up with errors on every scrape tick.
```
... context deadline exceeded (Client.Timeout exceeded while awaiting headers) ...
```
This can be easily validated so this PR adds check for desired port and **throws a single error** if port does not exist.
_Note: It's user error, so correct solution is to get rid of annotation, however, annotation might be static in third party packages therefore unnecessary overrides are needed till it's get fixed. In each case, this cloud help to have cleaner logs when user error occurs._

Do not target services with port that does not exist

---

.github/workflows/nightly.yaml

Successfully tested with the reusable workflow reusable_nightly.yaml.
PR needs to be merged after this https://github.com/newrelic/coreint-automation/pull/97 is merged.

Nr 341878 use reusable workflow for docker image security checks

---

.github/workflows/release-integration.yml
.github/workflows/security.yml

Tested the reusable workflow for pre releases.
This PR depends on https://github.com/newrelic/coreint-automation/pull/103
Merge that and then point the job to the correct branch before merging

release now uses reusable workflow

---

.github/workflows/nightly.yaml
.github/workflows/release-integration.yml

Pass slack channel and and slack token as secrets to the reusable nightly and image release workflows.

slack channel and token passed as secrets

---

.github/workflows/push_pr.yml

https://goreleaser.com/customization/builds/go/
```
#
goamd64:
- v2
- v3
#
goarm64:
- v9.0
#
gomips:
- hardfloat
- softfloat
#
go386:
- sse2
- softfloat
```

goreleaser adding version to binaries
